애플리케이션은 여러 예외 상황에 노출된다.

예외가 발생했을 때 적절히 처리되지 않으면 → 예측하지 못한 방향으로 동작하거나 비정상 종료될 수 있다.

⇒ 안정적인 애플리케이션을 위해서 예외를 적절하게 처리하는 것이 중요하다.

애플리케이션의 비동기 작업을 수행하는 코루틴의 예외 처리 또한 중요하다.

특히, 코루틴의 비동기 작업에서 자주 사용되는 네트워크 요청, 데이터 베이스 같은 I/O 작업을 수행할 때 예측할 수 없는 예외가 발생할 가능성이 높다.

1. 예외가 발생했을 때 코루틴이 어떻게 동작하는지 알아보고,
2. 예외를 처리하는 방법을 알아보자


## 코루틴의 예외 전파

코루틴 실행 도중 예외가 발생하면

1. 해당 코루틴은 취소된다.
2. 부모 코루틴으로 예외가 전파된다.
3. 부모 코루틴에서 예외가 처리되지 않으면 부모 코루틴도 취소된다.
4. 부모 코루틴의 상위(부모) 코루틴으로 예외가 전파된다.

… (반복)

1. 최상위 루트 코루틴까지 예외가 전파될 수 있다.

---

*코루틴이 취소요청되면 → 구조화로 인해 하위에 있는 모든 자식 코루틴들에게 취소요청이 전파된다.

> 코루틴의 예외 전파는 부모 방향으로만 전파된다.
>
>
> 코루틴의 취소 전파는 자식 방향으로만 전파된다.
>

|  | 전파 방향 | 전파 조건 | 설명 |
| --- | --- | --- | --- |
| 예외 | 자식 → 부모 | 자식에서 처리되지 않은 예외 발생 | 예외가 처리되지 않으면 계속 상위 코루틴으로 전파됨 → 루트  코루틴까지 예외가 전파될 수 있음 |
| 취소 | 부모 → 자식 | 부모에서 `Job.cancel()` 호출 | 모든 자식 코루틴들에게 취소 요청이 전파됨 |

⇒ 코루틴의 예외 전파를 막지 못하면 루트 코루틴까지 예외가 전파되고 루트 코루틴이 취소되어 구조화된 코루틴이 모두 취소될 수 있다.

### 예외전파 1 (제한 없이 예외 전파)

```mermaid
flowchart TB
A[runBlocking**]
B[Coroutine1]
C[Coroutine2]**
D**[Coroutine3]**

A --> B & C
B --> D

부모 ---> 자식
  
  %% 스타일 설정
	classDef default font-size:13px,stroke-width:0px,color:#111;
```

```kotlin
fun main() = runBlocking<Unit> {
    launch(CoroutineName("Coroutine1")) {
        launch(CoroutineName("Coroutine3")) {
            throw Exception("예외 발생")
        }
        delay(100L)
        printlnCurrentThreadNameWithText("코루틴 실행")
    }
    launch(CoroutineName("Coroutine2")) {
        delay(100L)
        printlnCurrentThreadNameWithText("코루틴 실행")
    }
    delay(1000L)
}
// output
Exception in thread "main" java.lang.Exception: 예외 발생
```

1. Coroutine3 예외 발생
    1. Coroutine3 에서 예외 처리x
    2. Coroutine3 코루틴 취소 (자식 코루틴없음)
2. Coroutine3 → Coroutine1 예외 전파
    1. Coroutine1 에서 예외 처리x
    2. Coroutine1 코루틴 취소 (자식 코루틴없음 ?)
3. Coroutine1 → runBlocking 예외 전파
    1. runBlocking 에서 예외 처리 x
    2. runBlocking 코루틴 취소 → 자식 코루틴 Coroutine2 취소 전파

## 코루틴 예외 전파 제한하기

코루틴의 구조화는 큰 작업을 작은 작업으로 나누는 방식으로 이루어진다.

작은 작업에서 발생한 예외로 인해 큰 작업이 취소되면 애플리케이션 안정성에 문제가 생길 수 있다.

### 예외전파 2 (새로운 Job 객체를 사용해 예외 전파 제한하기)

코루틴은 자신의 부모코루틴으로만 예외를 전파한다.

→ 새로운 Job객체를 context에 추가하면, 코루틴의 구조화(부모-자식 관계)가 깨져 예외 전파를 제한할 수 있다.

```kotlin
fun main() = runBlocking<Unit> {
    launch(CoroutineName("Parent Coroutine")) {
        launch(CoroutineName("Coroutine1") + Job()) {
            launch(CoroutineName("Coroutine3")) {
                throw Exception("예외 발생")
            }
            delay(100L)
            printlnCurrentThreadNameWithText("코루틴 실행")
        }
        launch(CoroutineName("Coroutine2")) {
            delay(100L)
            printlnCurrentThreadNameWithText("코루틴 실행")
        }
    }
    delay(1000L)
}
// output
Exception in thread "main @Coroutine1#3" java.lang.Exception: 예외 발생
[main @Coroutine2#4] 코루틴 실행
```

| 해결된 문제점 | 발생할 수 있는 문제점 |
| --- | --- |
| Parent Coroutine 으로 예외가 전파되지 않아 Coroutine2 가 정상실행된다. | 코루틴의 구조화가 깨진다. |

```mermaid
flowchart TB
A[runBlocking**]
B[Parent Coroutine]
C[Coroutine2]**
D**["Job()"]**
E[Coroutine1]
F[Coroutine3]

A --> B --> C

D --> E --> F

부모 ---> 자식
  
  %% 스타일 설정
	classDef default font-size:13px,stroke-width:0px,color:#111;
```

`한계점`

→ 코루틴의 구조화가 깨져 예외 전파를 제한할 뿐만 아니라, 취소 전파도 제한된다.

⇒ 큰작업에 취소요청이 들어와도 구조화가 깨진 작은 작업으로 취소가 전파되지 않는다.

1. Parent Coroutine 취소 요청 발생
2. Parent Coroutine의 자식 코루틴인 Coroutine2에 취소 요청 전파
3. Coroutine1, Coroutine3 정상실행 [문제점 발생]

```kotlin
fun main() = runBlocking<Unit> {
    val parentJob = launch(CoroutineName("Parent Coroutine")) {
        launch(CoroutineName("Coroutine1") + Job()) {
            launch(CoroutineName("Coroutine3")) {
                delay(100L)
                printlnCurrentThreadNameWithText("코루틴 실행")
            }
            delay(100L)
            printlnCurrentThreadNameWithText("코루틴 실행")
        }
        launch(CoroutineName("Coroutine2")) {
            delay(100L)
            printlnCurrentThreadNameWithText("코루틴 실행")
        }
    }
    delay(20L)
    parentJob.cancel()
    delay(1000L)
}
// output
[main @Coroutine1#3] 코루틴 실행
[main @Coroutine3#5] 코루틴 실행
```

### 예외전파 3 (SupervisorJob 객체를 사용해 예외 전파 제한하기)

구조화를 깨지 않으면서 예외 전파를 제한하는 방법

```kotlin
public fun SupervisorJob(parent: Job? = null) : CompletableJob = SupervisorJobImpl(parent)

private class SupervisorJobImpl(parent: Job?) : JobImpl(parent) {
    override fun childCancelled(cause: Throwable): Boolean = false
}
```

```kotlin
public fun Job(parent: Job? = null): CompletableJob = JobImpl(parent)
```

SupervisorJob과 Job의 차이는

`override fun childCancelled(cause: Throwable): Boolean = false` 밖에 없다.

~~→ child Cancellation을 무시, 자기 자신 취소 x, 예외처리x(→ 호출자[취소된 자식]가 예외 처리에 대한 책임을 진다.)~~

~~→ child의 coroutineExceptionHandler나 try-catch가 처리한다고?~~

```kotlin
/**
자식이 cause로 인해 취소되었다.

1. 이 메소드는 부모가 스스로를 취소할지말지 결정한다. (심각한 오류가 발생한 경우)
2. 자식의 예외를 처리할지 말지 결정한다.

Supervisor 구현들에서는 이 함수를 재정의해 완벽하게 자식 cancellation을 무시한다. (false)

true를 반환하면 예외가 처리된것이고,
false를 반환하면 호출자가 예외 처리에 대한 책임을 가진다. [취소된 자식]

불변규칙 : CancellationException에 대해서는 절대 false를 반환하면 안된다.
그렇지 않으면, 예외가 CoroutineExceptionHandler로 누출될 수 있다.
*/
public open fun childCancelled(cause: Throwable): Boolean {
    if (cause is CancellationException) return true
    return cancelImpl(cause) && handlesException
}
```

```kotlin
fun main() = runBlocking<Unit> {
    val supervisorJob = SupervisorJob()

    launch(CoroutineName("Coroutine1") + supervisorJob) {
        launch(CoroutineName("Coroutine3")) {
            throw Exception("예외 발생")
        }
        delay(100L)
        printlnCurrentThreadNameWithText("코루틴 실행")
    }

    launch(CoroutineName("Coroutine2") + supervisorJob) {
        delay(100L)
        printlnCurrentThreadNameWithText("코루틴 실행")

    }
    delay(1000L)
}
```

1. Coroutine3 예외 발생
    1. Coroutine3 취소완료
2. Coroutine3 → Coroutine1 예외 전파
    1. Corouitne1 취소완료
3. Coroutine1 → supervisorJob 예외 전달
4. supervisorJob에서 예외를 전파받지 않음 (`childCancelled`  false로 무시)
5. supervisorJob의 다른 자식 코루틴인 Coroutine2 정상 실행

```mermaid
flowchart TB
A[runBlocking**]
B[supervisorJob]
C[Coroutine1]**
D[Coroutine2]
E[Coroutine3]

A

B --> C & D

C --> E

부모 ---> 자식
  
  %% 스타일 설정
	classDef default font-size:13px,stroke-width:0px,color:#111;
```

runBlocking의 Job객체를 supervisorJob의 부모Job으로 설정

```kotlin
fun main() = runBlocking<Unit> {
		val supervisorJob = SupervisorJob(parent = this.coroutineContext[Job])
		...
		supervisorJob.complete() // Job()객체를
}
```

supervisorJob 명시적으로 완료 처리 →

GPT 대답) 코루틴 빌더가 자동으로 완료를 처리해주지 않기 때문

- 이건가?

    ```kotlin
    protected final override fun onCompletionInternal(state: Any?) {
            if (state is CompletedExceptionally)
                onCancelled(state.cause, state.handled)
            else
                onCompleted(state as T)
        }
    ```


```kotlin
/**
complete() 함수를 사용해 완료될 수 있다.
Job()과 SupervisorJob() 함수에 의해 반환된다.

이 interface의 모든 함수는 thread-safe하고 동시성 코루틴에서 외부 동기화없이 안전하게 호출될 수 있다.
*/
public interface CompletableJob : Job {
```

```mermaid
flowchart TB
A[runBlocking**]
B[supervisorJob]
C[Coroutine1]**
D[Coroutine2]
E[Coroutine3]

A --> B --> C & D

C --> E

부모 ---> 자식
  
  %% 스타일 설정
	classDef default font-size:13px,stroke-width:0px,color:#111;
```

| 해결된 문제점 | 발생할 수 있는 문제점 |
| --- | --- |
| 1. Parent Coroutine 으로 예외가 전파되지 않아 Coroutine2 가 정상실행된다. | SupervisorJob객체는 CompletableJob을 반환하기 때문에 명시적으로 complete() 함수를 호출해줘야한다. |
| 2. 코루틴의 구조화가 유지된다. |  |

### 예외전파 4. (supervisorScope  함수를 사용해 예외 전파 제한하기)

- SupervisorJob을 CoroutineScope와 함께 사용하기
    - SupervisorJob 객체를 가진 CoroutineScope가 생성됨
    - `coroutineScope` 의 환경을 Coroutine1,2가 상속받음

    ```kotlin
    fun main() = runBlocking<Unit> {
        val coroutineScope = CoroutineScope(SupervisorJob())
    
        coroutineScope.apply {
            launch(CoroutineName("Coroutine1")) {
                launch(CoroutineName("Coroutine3")) {
                    throw Exception("예외 발생")
                }
                delay(100L)
                printlnCurrentThreadNameWithText("코루틴 실행")
            }
    
            launch(CoroutineName("Coroutine2")) {
                delay(100L)
                printlnCurrentThreadNameWithText("코루틴 실행")
    
            }
        }
        delay(1000L)
    }
    ```

    ```mermaid
    flowchart TB
    A[runBlocking**]
    B[coroutineScope]
    C[Coroutine1]**
    D[Coroutine2]
    E[Coroutine3]
    
    A
    B --> C & D
    
    C --> E
    
    부모 ---> 자식
      
      %% 스타일 설정
    	classDef default font-size:13px,stroke-width:0px,color:#111;
    ```

- SupervisorJob을 사용할 때 흔히 하는 실수
    - Parent Coroutine - launch 코루틴빌더의 Job 객체는 SueprvisorJob객체를 부모로하는 새로운 Job객체이다.
    - 즉, Parent Coroutine의 Job은 SupervisorJob이 아니라는 뜻이다.
    - 그렇다면 → 예외를 전파 받는다.
        1. Parent Coroutine이 예외를 전파받음
        2. Parent Coroutine → SupervisorJob() 예외 전달 [SupervisorJob()은 예외를 전파받지 않는다 But, 의미가 없어짐]
        3. Parent Coroutine 취소 → 자식 코루틴 Coroutine2 취소전파

    ```kotlin
    fun main() = runBlocking<Unit> {
        launch(CoroutineName("Parent Coroutine") + SupervisorJob()) {
            launch(CoroutineName("Coroutine1")) {
                launch(CoroutineName("Coroutine3")) {
                    throw Exception("예외 발생")
                }
                delay(100L)
                printlnCurrentThreadNameWithText("코루틴 실행")
            }
    
            launch(CoroutineName("Coroutine2")) {
                delay(100L)
                printlnCurrentThreadNameWithText("코루틴 실행")
    
            }
        }
        delay(1000L)
    }
    ```

    ```mermaid
    flowchart TB
    A["SuperviosrJob()"**]
    B[Parent Coroutine]
    C[Coroutine1]**
    D[Coroutine2]
    E[Coroutine3]
    
    A --> B --> C & D
    
    C --> E
    
    부모 ---> 자식
      
      %% 스타일 설정
    	classDef default font-size:13px,stroke-width:0px,color:#111;
    ```


```kotlin
fun main() = runBlocking<Unit> {
    supervisorScope {
        launch(CoroutineName("Coroutine1")) {
            launch(CoroutineName("Coroutine3")) {
                throw Exception("예외 발생")
            }
            delay(100L)
            printlnCurrentThreadNameWithText("코루틴 실행")
        }

        launch(CoroutineName("Coroutine2")) {
            delay(100L)
            printlnCurrentThreadNameWithText("코루틴 실행")

        }
    }
}
```

```mermaid
flowchart TB
A[runBlocking**]
B[supervisorScope]
C[Coroutine1]**
D[Coroutine2]
E[Coroutine3]

A --> B --> C & D

C --> E

부모 ----> 자식
  
  %% 스타일 설정
	classDef default font-size:13px,stroke-width:0px,color:#111;
```

| 해결된 문제점 | 발생할 수 있는 문제점 |
| --- | --- |
| 1. Parent Coroutine 으로 예외가 전파되지 않아 Coroutine2 가 정상실행된다. | GPT1. 자식 코루틴의 예외가 “조용히” 무시될 수 있음 |
| 2. 코루틴의 구조화가 유지된다. |  |
| 3. 명시적으로 complete() 함수를 호출할 필요가 없다. |  |
| 4. SupervisorJob() 객체를 생성할 때 계층 구조상 어떤 위치에 있어야되는지 복잡하게 생각할 필요가 없다. |  |

## CoroutineExceptionHandler를 사용해 코루틴의 예외 처리하기

- CoroutineExceptionHandler는 CoroutineContext 객체의 구성요소
- CoroutineScope() 함수 호출 → 새로운 Job객체 생성 → runBlocking과 구조화 깨짐

```kotlin
fun main() = runBlocking<Unit> {
    val coroutineExceptionHandler = CoroutineExceptionHandler { coroutineContext, throwable ->
        println("[예외 발생] $throwable")
    }

    CoroutineScope(coroutineExceptionHandler).launch(CoroutineName("Coroutine1")) {
        throw Exception("Coroutine1에 예외가 발생했습니다.")
    }
    delay(1000L)
}
//output
[예외 발생] java.lang.Exception: Coroutine1에 예외가 발생했습니다.
```

```kotlin
handleException을 재정의

public inline fun CoroutineExceptionHandler(crossinline handler: (CoroutineContext, Throwable) -> Unit): CoroutineExceptionHandler =
    object : AbstractCoroutineContextElement(CoroutineExceptionHandler), CoroutineExceptionHandler {
        override fun handleException(context: CoroutineContext, exception: Throwable) =
            handler.invoke(context, exception)
    }
```

CoroutineScope에 coroutineExceptionHandler가 등록되고

Coroutine1으로 coroutineExceptionHandler가 상속된다.

```mermaid
flowchart TB
A[runBlocking**]
B[CoroutineScope]
C[Coroutine1]**

A
B --> C

부모 --> 자식
  
  %% 스타일 설정
	classDef default font-size:13px,stroke-width:0px,color:#111;
```

### CoroutineExceptionHandler는 처리되지 않은 예외만 처리한다.

처리된 예외

- 코루틴이 예외를 전파하면 처리된 예외로 간주
    - ex: 자식 코루틴이 부모 코루틴으로 예외를 전파하면 자식 코루틴은 예외가 처리된 것으로 간주

    1. Coroutine1 → runBlocking 예외 전파
    2. Coroutine1의 구성요소인 coroutineExceptionHandler는 동작 하지 않는다.

    ```kotlin
    fun main() = runBlocking<Unit> {
        val coroutineExceptionHandler = CoroutineExceptionHandler { coroutineContext, throwable ->
            println("[예외 발생] $throwable")
        }
    
        launch(CoroutineName("Coroutine1") + coroutineExceptionHandler) {
            throw Exception("Coroutine1에 예외가 발생했습니다.")
        }
        delay(1000L)
    }
    ```


### CoroutineExceptionHandler가 예외를 처리하도록 만들기

예외가 마지막으로 전파되는 위치에 CoroutineExceptionHandler 객체를 설정하면 동작한다.

1. 새로운 Job을 만들기
    - coroutineContext는 루트 Job을 가짐 → 예외가 마지막으로 전파되는 위치 → CoroutineExceptionHandler 동작

```kotlin
fun main() = runBlocking<Unit> {
    val coroutineContext = Job() + CoroutineExceptionHandler { coroutineContext, throwable ->
        println("[예외 발생] $throwable")
    }

    launch(CoroutineName("Coroutine1") + coroutineContext) {
        throw Exception("Coroutine1에 예외가 발생했습니다.")
    }
    
    delay(1000L)
}
// output
[예외 발생] java.lang.Exception: Coroutine1에 예외가 발생했습니다.
```

1. SupervisorJob과 CoroutineExceptionHandler 함께 사용
    - SupervisorJob으로 예외 전파x
    - SupervisorJob으로 예외 전달o

    ```kotlin
    fun main() = runBlocking<Unit> {
        val exceptionHandler = CoroutineExceptionHandler { coroutineContext, throwable ->
            println("[예외 발생] $throwable")
        }
    
        val supervisedScope = CoroutineScope(SupervisorJob() + exceptionHandler)
    
        supervisedScope.apply {
            launch(CoroutineName("Coroutine1")) {
                throw Exception("Coroutine1에 예외가 발생했습니다.")
            }
            launch(CoroutineName("Coroutine2")) {
                delay(100L)
                printlnCurrentThreadNameWithText("코루틴 실행")
            }
        }
    
        delay(1000L)
    }
    // output
    [예외 발생] java.lang.Exception: Coroutine1에 예외가 발생했습니다.
    [DefaultDispatcher-worker-1 @Coroutine2#3] 코루틴 실행
    ```


### CoroutineExceptionHandler는 예외 전파를 제한하지 않는다.

try-catch문 처럼 예외전파를 제한하지 않는다.

예외가 마지막으로 처리되는 위치에서 예외를 처리할 뿐이다.

```kotlin
fun main() = runBlocking<Unit> {
    val exceptionHandler = CoroutineExceptionHandler { coroutineContext, throwable ->
        println("[예외 발생] $throwable")
    }
    launch(CoroutineName("Coroutine1") + exceptionHandler) {
        throw Exception("Coroutine1에 예외가 발생했습니다.")
    }
    delay(1000L)
}
// output
// 예외가 runBlocking으로 전파되어 프로세스가 비정상 종료됨 (예외 전파를 제한하지 않는다.)
Exception in thread "main" java.lang.Exception: Coroutine1에 예외가 발생했습니다.
```

### try-catch 문을 사용해 코루틴 예외 처리하기

- Coroutine1에서 발생한 예외는 try-catch로 처리됨

  → 처리된 예외는 전파되지 않는다.

    ```kotlin
    fun main() = runBlocking<Unit> {
    
        launch(CoroutineName("Coroutine1")) {
            try {
                throw Exception("Coroutine1에 예외가 발생했습니다.")
    
            } catch (e: Exception) {
                println(e.message)
            }
        }
        launch(CoroutineName("Coroutine2")) {
            delay(100L)
            println("실행 완료")
        }
        delay(1000L)
    }
    
    // output
    Coroutine1에 예외가 발생했습니다.
    실행 완료
    ```


- 코루틴 빌더함수에 대한 try-catch문은 예외를 잡지 못한다.
    - launch는 코루틴을 생성하는데 사용되는 함수일 뿐이다.
    - 람다식의 실행은 생성된 코루틴이 CoroutineDispatcher에 의해 스레드로 분배되는 시점에 일어난다.
    - 즉, 이 try-catch문은 launch 코루틴 빌더 함수 자체의 실행만 체크한다.

    ```kotlin
    fun main() = runBlocking<Unit> {
    
        try {
            launch(CoroutineName("Coroutine1")) {
                throw Exception("Coroutine1에 예외가 발생했습니다.")
            }
        } catch (e: Exception) {
            println(e.message)
        }
        
        launch(CoroutineName("Coroutine2")) {
            delay(100L)
            println("실행 완료")
        }
        delay(1000L)
    }
    // output
    // runBlocking으로 예외가전파되어 Coroutine2까지 취소시키고 프로세스가 비정상 종료됨
    Exception in thread "main" java.lang.Exception: Coroutine1에 예외가 발생했습니다.
    ```


## async 예외처리

- aysnc 코루틴 빌더 함수는 결괏값을 Deferred 객체로 감싸고 await 호출 시점에 결괏값을 노출한다.
    - 코루틴 실행 도중 예외가 발생해 결괏값이 없다면 Deferred에 대한 await 호출시 예외가 노출된다.

  → await() 호출부를 try/catch로 감싼다.

  [코루틴 빌더를 호출해 만들어진 코루틴에서 예외가 발생할 경우 await 호출부에서 예외처리를 해준다. → 왜? 이유가뭔데

    ```kotlin
    fun main() = runBlocking<Unit> {
        supervisorScope {
            val deferred = async(CoroutineName("Coroutine1")) {
                throw Exception("Coroutine1에 예외가 발생했습니다.")
            }
            try {
                deferred.await()
            } catch (e: Exception) {
                println(e.message)
            }
        }
    }
    // output
    Coroutine1에 예외가 발생했습니다.
    ```


- Coroutine1 이 supervisorCope로 인해 예외 전파를 제한받아 Coroutine2가 정상실행
    - async는 전파되는 예외와 await 호출 시 노출되는 예외 모두 처리해줘야 한다.

```kotlin
fun main() = runBlocking<Unit> {
    supervisorScope {
        async(CoroutineName("Coroutine1")) {
            throw Exception("Coroutine1에 예외가 발생했습니다.")
        }

        launch(CoroutineName("Coroutine2")) {
            printlnCurrentThreadNameWithText("코루틴 실행")
        }
    }
}
// output
[main @Coroutine2#3] 코루틴 실행
```

## CancellationException은 전파되지 않는 예외이다.

CancellationException은 정상동작으로 간주한다.

코루틴 취소에 사용되는 특별한 예외이다.

```kotlin
public open fun childCancelled(cause: Throwable): Boolean {
    if (cause is ***CancellationException***) return true
    return cancelImpl(cause) && handlesException
}
```

코루틴 취소시 사용되는 JobCancellationException은 CancellationException의 서브클래스이다.

### withTimeout은 TimeoutCancellation을 발생시킨다.

TimeoutCancellation은 CancellationException의 서브클래스이다.

- 코루틴 예외가 어떻게 처리되는지 내부구현확인

    ```kotlin
    private open class StandaloneCoroutine(
        parentContext: CoroutineContext,
        active: Boolean
    ) : AbstractCoroutine<Unit>(parentContext, initParentJob = true, active = active) {
        override fun handleJobException(exception: Throwable): Boolean {
            handleCoroutineException(context, exception)
            return true
        }
    }
    ```

    ```kotlin
    @InternalCoroutinesApi
    public fun handleCoroutineException(context: CoroutineContext, exception: Throwable) {
        val reportException = if (exception is DispatchException) exception.cause else exception
        // Invoke an exception handler from the context if present
        try {
            context[CoroutineExceptionHandler]?.let {
                it.handleException(context, reportException)
                return
            }
        } catch (t: Throwable) {
            handleUncaughtCoroutineException(context, handlerException(reportException, t))
            return
        }
        // If a handler is not present in the context or an exception was thrown, fallback to the global handler
        handleUncaughtCoroutineException(context, reportException)
    }
    ```

- coroutineScope 내부구현살펴보기 <어떻게 CoroutineScope가 동작되는거지?>

    ```kotlin
    public suspend fun <R> coroutineScope(block: suspend CoroutineScope.() -> R): R {
        contract {
            callsInPlace(block, InvocationKind.EXACTLY_ONCE)
        }
        return suspendCoroutineUninterceptedOrReturn { uCont ->
            val coroutine = ScopeCoroutine(uCont.context, uCont)
            @Suppress("LEAKED_IN_PLACE_LAMBDA") // Contract is preserved, invoked immediately or throws
            coroutine.startUndispatchedOrReturn(coroutine, block)
        }
    }
    ```

    ```kotlin
    internal open class ScopeCoroutine<in T>(
        context: CoroutineContext,
        @JvmField val uCont: Continuation<T> // unintercepted continuation
    ) : AbstractCoroutine<T>(context, true, true), CoroutineStackFrame {
    
        final override val callerFrame: CoroutineStackFrame? get() = uCont as? CoroutineStackFrame
        final override fun getStackTraceElement(): StackTraceElement? = null
    
        final override val isScopedCoroutine: Boolean get() = true
    
        override fun afterCompletion(state: Any?) {
            // Resume in a cancellable way by default when resuming from another context
            uCont.intercepted().resumeCancellableWith(recoverResult(state, uCont))
        }
    
        /**
         * Invoked when a scoped coorutine was completed in an undispatched manner directly
         * at the place of its start because it never suspended.
         */
        open fun afterCompletionUndispatched() {
        }
    
        override fun afterResume(state: Any?) {
            // Resume direct because scope is already in the correct context
            uCont.resumeWith(recoverResult(state, uCont))
        }
    }
    ```

- supervisorScope

    ```kotlin
    public suspend fun <R> supervisorScope(block: suspend CoroutineScope.() -> R): R {
        contract {
            callsInPlace(block, InvocationKind.EXACTLY_ONCE)
        }
        return suspendCoroutineUninterceptedOrReturn { uCont ->
            val coroutine = SupervisorCoroutine(uCont.context, uCont)
            @Suppress("LEAKED_IN_PLACE_LAMBDA") // Contract is preserved, invoked immediately or throws
            coroutine.startUndispatchedOrReturn(coroutine, block)
        }
    }
    ```

    ```kotlin
    private class SupervisorCoroutine<in T>(
        context: CoroutineContext,
        uCont: Continuation<T>
    ) : ScopeCoroutine<T>(context, uCont) {
        override fun childCancelled(cause: Throwable): Boolean = false
    }
    ```